# Generated by Django 5.0.6 on 2024-07-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_value_review_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='project',
            new_name='blog',
        ),
    ]
